pipeline {
    agent {
        docker {
            image 'node:current-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('docker build/push') {
             steps {
                docker.withRegistry('https://index.docker.io/v2/', 'docker-hub') {
                def app = docker.build("ikaushik96/nodeapp:${commit_id}", '.').push()
                }
            }
        }
    //     stage('Deliver') {
    //         steps {
    //             sh './jenkins/scripts/deliver.sh'
    //             input message: 'Finished using the web site? (Click "Proceed" to continue)'
    //             //sh './jenkins/scripts/kill.sh'
    //         }
    //     }
    }
}
